# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ec85181d4af3583eb5b88a42498c985c4b48412614aef2d5215ea521f7a2d858adcf568c2fecaa16fc86dace877fdb4f71facbd3b97b393998a09308a14b51

test:
  secret_key_base: 1f7828d17ddb5545b5e136c67ad120bca75c0113b575925f738cf05016b683dc39533a871876d27523edc8ad8d75607cb124139bcbd050eeebdcb92828a1976b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
